#!/bin/bash
echo "Starting Dev Environment..."
echo "Starting client..."
trap 'kill %1' SIGINT
cd $HOME/pa-os-desktopclient
google-chrome-stable --new-window http://localhost:9222 & 
npm run watch start & 
echo "Starting databases..."
sudo service neo4j start
sudo service mysql start
mongod --dbpath=$HOME/pa-os-server/doc-data
echo "Started databases."
cd $HOME/pa-os-server
npm run watch start 
echo "Shutting down client..."
echo "Closing Dev Environment..."
echo "Done."
trap SIGINT

